/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tabla.periodica.proyecto;



/**
 *
 * @author Adrian_Alejandro
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        setLocationRelativeTo(this);
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Iratabla = new javax.swing.JButton();
        Iratabla1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Iratabla.setBackground(new java.awt.Color(0, 153, 102));
        Iratabla.setFont(new java.awt.Font("Eras Demi ITC", 0, 13)); // NOI18N
        Iratabla.setText("Ir a tabla periódica");
        Iratabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Iratabla.setSelected(true);
        Iratabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IratablaActionPerformed(evt);
            }
        });
        getContentPane().add(Iratabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 147, 76));

        Iratabla1.setBackground(new java.awt.Color(0, 153, 102));
        Iratabla1.setFont(new java.awt.Font("Eras Demi ITC", 0, 13)); // NOI18N
        Iratabla1.setText("Salir");
        Iratabla1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Iratabla1.setSelected(true);
        Iratabla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Iratabla1ActionPerformed(evt);
            }
        });
        getContentPane().add(Iratabla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 147, 76));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/galaxia.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IratablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IratablaActionPerformed
        Tabla window=new Tabla();
        window.setTitle("Tabla periódica");
        window.setVisible(true);
        dispose();
    }//GEN-LAST:event_IratablaActionPerformed

    private void Iratabla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iratabla1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Iratabla1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Iratabla;
    private javax.swing.JButton Iratabla1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
