/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tabla.periodica.proyecto;



/**
 *
 * @author Adrian_Alejandro
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(this.MAXIMIZED_BOTH);
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Iratabla1 = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        getContentPane().setLayout(null);

        Iratabla1.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        Iratabla1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/abstract-green-background-free-vector.jpg"))); // NOI18N
        Iratabla1.setText("Ir a la tabla");
        Iratabla1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 5, 5), 3));
        Iratabla1.setContentAreaFilled(false);
        Iratabla1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Iratabla1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Iratabla1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/verde abstracto brillar.jpg"))); // NOI18N
        Iratabla1.setSelected(true);
        Iratabla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Iratabla1ActionPerformed(evt);
            }
        });
        getContentPane().add(Iratabla1);
        Iratabla1.setBounds(880, 280, 240, 76);

        Salir.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/abstract-green-background-free-vector.jpg"))); // NOI18N
        Salir.setText("Salir");
        Salir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 5, 5), 3));
        Salir.setContentAreaFilled(false);
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Salir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/verde abstracto brillar.jpg"))); // NOI18N
        Salir.setSelected(true);
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir);
        Salir.setBounds(880, 460, 240, 76);

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setText("¡¡¡BIENVENIDO!!!");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(810, 150, 540, 130);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/inicio.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(2930, 1150));
        jLabel1.setMinimumSize(new java.awt.Dimension(1920, 1150));
        jLabel1.setPreferredSize(new java.awt.Dimension(1920, 1150));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-30, -50, 2000, 1180);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Iratabla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iratabla1ActionPerformed
         Tabla window=new Tabla();
        window.setTitle("Tabla periódica de los elementos");
        window.setVisible(true);
        dispose();
    }//GEN-LAST:event_Iratabla1ActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Iratabla1;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
