/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tabla.periodica.proyecto;

import java.awt.Toolkit;

/**
 *
 * @author Adrian_Alejandro
 */
public class Seriedelantanidos extends javax.swing.JFrame {

    /**
     * Creates new form Seriedelantanidos
     */
    public Seriedelantanidos() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        La = new javax.swing.JButton();
        Pr = new javax.swing.JButton();
        Nd = new javax.swing.JButton();
        Ce = new javax.swing.JButton();
        Pm = new javax.swing.JButton();
        Sm = new javax.swing.JButton();
        Eu = new javax.swing.JButton();
        Gd = new javax.swing.JButton();
        Tb = new javax.swing.JButton();
        Dy = new javax.swing.JButton();
        Ho = new javax.swing.JButton();
        Er = new javax.swing.JButton();
        Tm = new javax.swing.JButton();
        Yb = new javax.swing.JButton();
        Lu = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        T7 = new javax.swing.JTextField();
        T6 = new javax.swing.JTextField();
        T10 = new javax.swing.JTextField();
        T8 = new javax.swing.JTextField();
        T9 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        La.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        La.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        La.setText("La");
        La.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        La.setName(""); // NOI18N
        La.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaActionPerformed(evt);
            }
        });

        Pr.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        Pr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        Pr.setText("Pr");
        Pr.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Pr.setName(""); // NOI18N
        Pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrActionPerformed(evt);
            }
        });

        Nd.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        Nd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        Nd.setText("Nd");
        Nd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Nd.setName(""); // NOI18N
        Nd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NdActionPerformed(evt);
            }
        });

        Ce.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        Ce.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        Ce.setText("Ce");
        Ce.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Ce.setName(""); // NOI18N
        Ce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CeActionPerformed(evt);
            }
        });

        Pm.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        Pm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        Pm.setText("Pm");
        Pm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Pm.setName(""); // NOI18N
        Pm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PmActionPerformed(evt);
            }
        });

        Sm.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        Sm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        Sm.setText("Sm");
        Sm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Sm.setName(""); // NOI18N
        Sm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmActionPerformed(evt);
            }
        });

        Eu.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        Eu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        Eu.setText("Eu");
        Eu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Eu.setName(""); // NOI18N
        Eu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EuActionPerformed(evt);
            }
        });

        Gd.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        Gd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        Gd.setText("Gd");
        Gd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Gd.setName(""); // NOI18N
        Gd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GdActionPerformed(evt);
            }
        });

        Tb.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        Tb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        Tb.setText("Tb");
        Tb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tb.setName(""); // NOI18N
        Tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TbActionPerformed(evt);
            }
        });

        Dy.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        Dy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        Dy.setText("Dy");
        Dy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Dy.setName(""); // NOI18N
        Dy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DyActionPerformed(evt);
            }
        });

        Ho.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        Ho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        Ho.setText("Ho");
        Ho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Ho.setName(""); // NOI18N
        Ho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoActionPerformed(evt);
            }
        });

        Er.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        Er.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        Er.setText("Er");
        Er.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Er.setName(""); // NOI18N
        Er.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ErActionPerformed(evt);
            }
        });

        Tm.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        Tm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        Tm.setText("Tm");
        Tm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tm.setName(""); // NOI18N
        Tm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TmActionPerformed(evt);
            }
        });

        Yb.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        Yb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        Yb.setText("Yb");
        Yb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Yb.setName(""); // NOI18N
        Yb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YbActionPerformed(evt);
            }
        });

        Lu.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        Lu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        Lu.setText("Lu");
        Lu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Lu.setName(""); // NOI18N
        Lu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 102));
        jButton1.setFont(new java.awt.Font("Eras Demi ITC", 3, 13)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        jLabel1.setText("Nombre: ");

        jLabel2.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        jLabel2.setText("N. Atómico:");

        jLabel3.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        jLabel3.setText("Periodo:");

        jLabel4.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        jLabel4.setText("Masa atómica:");

        jLabel5.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        jLabel5.setText("Familia:");

        T7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                T7KeyTyped(evt);
            }
        });

        T6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                T6KeyTyped(evt);
            }
        });

        T10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                T10KeyTyped(evt);
            }
        });

        T8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                T8KeyTyped(evt);
            }
        });

        T9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                T9KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(T6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(T7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(T10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(T8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(T9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(La, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ce, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pr, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Nd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pm, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Sm, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Eu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Gd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tb, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Dy, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ho, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Er, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tm, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Yb, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(T7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(T8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(T6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(T9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(T10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(La, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ce, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pr, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nd, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pm, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sm, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gd, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tb, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dy, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ho, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Er, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tm, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Yb, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Tabla window=new Tabla();
        window.setTitle("Tabla periódica de los elementos");
        window.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void T6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_T6KeyTyped
        if(T6.getText().length()>=0){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_T6KeyTyped

    private void T7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_T7KeyTyped
        if(T7.getText().length()>=0){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_T7KeyTyped

    private void T8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_T8KeyTyped
        if(T8.getText().length()>=0){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_T8KeyTyped

    private void T9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_T9KeyTyped
        if(T9.getText().length()>=0){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_T9KeyTyped

    private void T10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_T10KeyTyped
        if(T10.getText().length()>=0){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_T10KeyTyped

    private void LaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaActionPerformed
        T6.setText("Lantano");
        T7.setText("57");
        T8.setText("138.90547 u");
        T9.setText("6");
        T10.setText("IIIB");
    }//GEN-LAST:event_LaActionPerformed

    private void CeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CeActionPerformed
        T6.setText("Cerio");
        T7.setText("58");
        T8.setText("140.116 u");
        T9.setText("6");
        T10.setText("IIIB");
    }//GEN-LAST:event_CeActionPerformed

    private void PrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrActionPerformed
        T6.setText("Praseodimio");
        T7.setText("59");
        T8.setText("140.90766 u");
        T9.setText("6");
        T10.setText("IIIB");
    }//GEN-LAST:event_PrActionPerformed

    private void NdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NdActionPerformed
        T6.setText("Neodimio");
        T7.setText("60");
        T8.setText("144.907666 u");
        T9.setText("6");
        T10.setText("IIIB");
    }//GEN-LAST:event_NdActionPerformed

    private void PmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PmActionPerformed
        T6.setText("Prometio");
        T7.setText("61");
        T8.setText("145 u");
        T9.setText("6");
        T10.setText("IIIB");
    }//GEN-LAST:event_PmActionPerformed

    private void SmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmActionPerformed
        T6.setText("Samario");
        T7.setText("62");
        T8.setText("150.36 u");
        T9.setText("6");
        T10.setText("IIIB");
    }//GEN-LAST:event_SmActionPerformed

    private void EuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EuActionPerformed
        T6.setText("Europio");
        T7.setText("63");
        T8.setText("151.964 u");
        T9.setText("6");
        T10.setText("IIIB");
    }//GEN-LAST:event_EuActionPerformed

    private void GdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GdActionPerformed
        T6.setText("Gadolinio");
        T7.setText("64");
        T8.setText("157.25 u");
        T9.setText("6");
        T10.setText("IIIB");
    }//GEN-LAST:event_GdActionPerformed

    private void TbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TbActionPerformed
        T6.setText("Terbio");
        T7.setText("65");
        T8.setText("158.92535 u");
        T9.setText("6");
        T10.setText("IIIB");
    }//GEN-LAST:event_TbActionPerformed

    private void DyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DyActionPerformed
        T6.setText("Disprosio");
        T7.setText("66");
        T8.setText("162.500 u");
        T9.setText("6");
        T10.setText("IIIB");
    }//GEN-LAST:event_DyActionPerformed

    private void HoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoActionPerformed
        T6.setText("Holmio");
        T7.setText("67");
        T8.setText("164.93033 u");
        T9.setText("6");
        T10.setText("IIIB");
    }//GEN-LAST:event_HoActionPerformed

    private void ErActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ErActionPerformed
        T6.setText("Erbio");
        T7.setText("68");
        T8.setText("167.259 u");
        T9.setText("6");
        T10.setText("IIIB");
    }//GEN-LAST:event_ErActionPerformed

    private void TmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TmActionPerformed
        T6.setText("Tulio");
        T7.setText("69");
        T8.setText("168.93422 u");
        T9.setText("6");
        T10.setText("IIIB");
    }//GEN-LAST:event_TmActionPerformed

    private void YbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YbActionPerformed
        T6.setText("Iterbio");
        T7.setText("70");
        T8.setText("173.045 u");
        T9.setText("6");
        T10.setText("IIIB");
    }//GEN-LAST:event_YbActionPerformed

    private void LuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuActionPerformed
        T6.setText("Lutecio");
        T7.setText("71");
        T8.setText("174.9668 u");
        T9.setText("6");
        T10.setText("IIIB");
    }//GEN-LAST:event_LuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seriedelantanidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seriedelantanidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seriedelantanidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seriedelantanidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seriedelantanidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ce;
    private javax.swing.JButton Dy;
    private javax.swing.JButton Er;
    private javax.swing.JButton Eu;
    private javax.swing.JButton Gd;
    private javax.swing.JButton Ho;
    private javax.swing.JButton La;
    private javax.swing.JButton Lu;
    private javax.swing.JButton Nd;
    private javax.swing.JButton Pm;
    private javax.swing.JButton Pr;
    private javax.swing.JButton Sm;
    private javax.swing.JTextField T10;
    private javax.swing.JTextField T6;
    private javax.swing.JTextField T7;
    private javax.swing.JTextField T8;
    private javax.swing.JTextField T9;
    private javax.swing.JButton Tb;
    private javax.swing.JButton Tm;
    private javax.swing.JButton Yb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
