/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tabla.periodica.proyecto;

import java.awt.Toolkit;

/**
 *
 * @author Adrian_Alejandro
 */
public class Seriedeactinidos extends javax.swing.JFrame {

    /**
     * Creates new form Seriedeactinidos
     */
    public Seriedeactinidos() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ac = new javax.swing.JButton();
        Th = new javax.swing.JButton();
        Pa = new javax.swing.JButton();
        U = new javax.swing.JButton();
        Pu = new javax.swing.JButton();
        Am = new javax.swing.JButton();
        Cm = new javax.swing.JButton();
        Np = new javax.swing.JButton();
        Cf = new javax.swing.JButton();
        Es = new javax.swing.JButton();
        Fm = new javax.swing.JButton();
        Bk = new javax.swing.JButton();
        Md = new javax.swing.JButton();
        No = new javax.swing.JButton();
        Lr = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        T11 = new javax.swing.JTextField();
        T12 = new javax.swing.JTextField();
        T14 = new javax.swing.JTextField();
        T13 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        T15 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Ac.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        Ac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        Ac.setText("Ac");
        Ac.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Ac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcActionPerformed(evt);
            }
        });

        Th.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        Th.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        Th.setText("Th");
        Th.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Th.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThActionPerformed(evt);
            }
        });

        Pa.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        Pa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        Pa.setText("Pa");
        Pa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Pa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaActionPerformed(evt);
            }
        });

        U.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        U.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        U.setText("U");
        U.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UActionPerformed(evt);
            }
        });

        Pu.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        Pu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        Pu.setText("Pu");
        Pu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Pu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuActionPerformed(evt);
            }
        });

        Am.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        Am.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        Am.setText("Am");
        Am.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Am.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmActionPerformed(evt);
            }
        });

        Cm.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        Cm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        Cm.setText("Cm");
        Cm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Cm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmActionPerformed(evt);
            }
        });

        Np.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        Np.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        Np.setText("Np");
        Np.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Np.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NpActionPerformed(evt);
            }
        });

        Cf.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        Cf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        Cf.setText("Cf");
        Cf.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Cf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CfActionPerformed(evt);
            }
        });

        Es.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        Es.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        Es.setText("Es");
        Es.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Es.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EsActionPerformed(evt);
            }
        });

        Fm.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        Fm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        Fm.setText("Fm");
        Fm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Fm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FmActionPerformed(evt);
            }
        });

        Bk.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        Bk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        Bk.setText("Bk");
        Bk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Bk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BkActionPerformed(evt);
            }
        });

        Md.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        Md.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        Md.setText("Md");
        Md.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Md.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MdActionPerformed(evt);
            }
        });

        No.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        No.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        No.setText("No");
        No.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoActionPerformed(evt);
            }
        });

        Lr.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        Lr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Botón amarillo.png"))); // NOI18N
        Lr.setText("Lr");
        Lr.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Lr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LrActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        jLabel1.setText("Nombre: ");

        jLabel2.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        jLabel2.setText("Periodo");

        jLabel3.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        jLabel3.setText("N. Atómico");

        jLabel4.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        jLabel4.setText("Masa atómica:");

        T11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                T11KeyTyped(evt);
            }
        });

        T12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                T12KeyTyped(evt);
            }
        });

        T14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                T14KeyTyped(evt);
            }
        });

        T13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                T13KeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        jLabel5.setText("Familia");

        T15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                T15KeyTyped(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 102));
        jButton1.setFont(new java.awt.Font("Eras Demi ITC", 3, 13)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(Ac, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Th, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(U, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Np, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Am, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cm, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bk, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cf, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Es, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fm, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Md, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(No, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lr, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addGap(472, 472, 472)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(T15, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T14, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(T11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(T12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(T13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(T14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(T15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ac, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Th, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pa, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(U, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Np, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Am, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cm, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bk, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cf, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Es, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fm, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Md, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(No, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lr, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void T11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_T11KeyTyped
        if(T11.getText().length()>=0){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_T11KeyTyped

    private void T12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_T12KeyTyped
        if(T12.getText().length()>=0){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_T12KeyTyped

    private void T13KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_T13KeyTyped
        if(T13.getText().length()>=0){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_T13KeyTyped

    private void T14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_T14KeyTyped
        if(T14.getText().length()>=0){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_T14KeyTyped

    private void T15KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_T15KeyTyped
        if(T15.getText().length()>=0){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_T15KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Tabla window=new Tabla();
        window.setTitle("Tabla periódica de los elementos");
        window.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcActionPerformed
        T11.setText("Actinio");
        T12.setText("89");
        T13.setText("227 u");
        T14.setText("7");
        T15.setText("IIIB");
    }//GEN-LAST:event_AcActionPerformed

    private void ThActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThActionPerformed
        T11.setText("Torio");
        T12.setText("90");
        T13.setText("232.0377 u");
        T14.setText("7");
        T15.setText("IIIB");
    }//GEN-LAST:event_ThActionPerformed

    private void PaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaActionPerformed
        T11.setText("Protactinio");
        T12.setText("91");
        T13.setText("231.03588 u");
        T14.setText("7");
        T15.setText("IIIB");
    }//GEN-LAST:event_PaActionPerformed

    private void UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UActionPerformed
        T11.setText("Uranio");
        T12.setText("92");
        T13.setText("238.02891 u");
        T14.setText("7");
        T15.setText("IIIB");
    }//GEN-LAST:event_UActionPerformed

    private void NpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NpActionPerformed
        T11.setText("Neptunio");
        T12.setText("93");
        T13.setText("237 u");
        T14.setText("7");
        T15.setText("IIIB");
    }//GEN-LAST:event_NpActionPerformed

    private void PuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuActionPerformed
        T11.setText("Plutonio");
        T12.setText("94");
        T13.setText("244 u");
        T14.setText("7");
        T15.setText("IIIB");
    }//GEN-LAST:event_PuActionPerformed

    private void AmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmActionPerformed
        T11.setText("Amercio");
        T12.setText("95");
        T13.setText("243 u");
        T14.setText("7");
        T15.setText("IIIB");
    }//GEN-LAST:event_AmActionPerformed

    private void CmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmActionPerformed
        T11.setText("Curio");
        T12.setText("96");
        T13.setText("247 u");
        T14.setText("7");
        T15.setText("IIIB");
    }//GEN-LAST:event_CmActionPerformed

    private void BkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BkActionPerformed
        T11.setText("Berkelio");
        T12.setText("97");
        T13.setText("247 u");
        T14.setText("7");
        T15.setText("IIIB");
    }//GEN-LAST:event_BkActionPerformed

    private void CfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CfActionPerformed
        T11.setText("Californio");
        T12.setText("98");
        T13.setText("251 u");
        T14.setText("7");
        T15.setText("IIIB");
    }//GEN-LAST:event_CfActionPerformed

    private void EsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EsActionPerformed
        T11.setText("Einstenio");
        T12.setText("99");
        T13.setText("252 u");
        T14.setText("7");
        T15.setText("IIIB");
    }//GEN-LAST:event_EsActionPerformed

    private void FmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FmActionPerformed
        T11.setText("Fermio");
        T12.setText("100");
        T13.setText("257 u");
        T14.setText("7");
        T15.setText("IIIB");
    }//GEN-LAST:event_FmActionPerformed

    private void MdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MdActionPerformed
        T11.setText("Mendelevio");
        T12.setText("101");
        T13.setText("258 u");
        T14.setText("7");
        T15.setText("IIIB");
    }//GEN-LAST:event_MdActionPerformed

    private void NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoActionPerformed
        T11.setText("Nobelio");
        T12.setText("102");
        T13.setText("259 u");
        T14.setText("7");
        T15.setText("IIIB");
    }//GEN-LAST:event_NoActionPerformed

    private void LrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LrActionPerformed
        T11.setText("Laurencio");
        T12.setText("103");
        T13.setText("262 u");
        T14.setText("7");
        T15.setText("IIIB");
    }//GEN-LAST:event_LrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seriedeactinidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seriedeactinidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seriedeactinidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seriedeactinidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seriedeactinidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ac;
    private javax.swing.JButton Am;
    private javax.swing.JButton Bk;
    private javax.swing.JButton Cf;
    private javax.swing.JButton Cm;
    private javax.swing.JButton Es;
    private javax.swing.JButton Fm;
    private javax.swing.JButton Lr;
    private javax.swing.JButton Md;
    private javax.swing.JButton No;
    private javax.swing.JButton Np;
    private javax.swing.JButton Pa;
    private javax.swing.JButton Pu;
    private javax.swing.JTextField T11;
    private javax.swing.JTextField T12;
    private javax.swing.JTextField T13;
    private javax.swing.JTextField T14;
    private javax.swing.JTextField T15;
    private javax.swing.JButton Th;
    private javax.swing.JButton U;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
